/**
 * Built-in autocomplete suggestions for the Spec Builder attribute fields, keyed to match
 * `AttributesSchema` in `src/schemas/character.schema.ts`. These ship so a fresh install has
 * useful autocomplete before any `config.yaml` customization; user-configured values in the
 * `character-attributes` config section supplement (or add duplicates that get de-duped
 * against) these lists rather than replacing them.
 */
export const DEFAULT_ATTRIBUTE_SUGGESTIONS: Record<string, string[]> = {
  sex: ['Male', 'Female', 'Androgynous', 'Non-binary'],
  apparent_age: [
    'Early 20s',
    'Mid 20s',
    'Late 20s',
    'Early 30s',
    'Mid 30s',
    'Late 30s',
    'Early 40s',
    'Mid 40s',
    'Late 40s',
    '50s',
    '60s',
    'Teens',
  ],
  ethnicity: [
    'American',
    'British',
    'French',
    'German',
    'Italian',
    'Spanish',
    'Irish',
    'Scandinavian',
    'Eastern European',
    'Slavic',
    'Mediterranean',
    'Middle Eastern',
    'Japanese',
    'Chinese',
    'Korean',
    'Southeast Asian',
    'South Asian',
    'African',
    'Afro-Caribbean',
    'Latin American',
    'Mexican',
    'Brazilian',
    'Pacific Islander',
    'Indigenous American',
    'Mixed heritage',
    'Elf',
    'Half-elf',
    'Orc',
    'Dwarf',
    'Fantasy human',
  ],
  skin_tone: [
    'Fair, neutral undertone',
    'Fair, cool undertone',
    'Fair, warm undertone',
    'Light, warm undertone',
    'Medium, olive undertone',
    'Medium, warm undertone',
    'Tan, warm undertone',
    'Deep, warm undertone',
    'Deep, neutral undertone',
    'Porcelain',
    'Freckled',
  ],
  face_shape: [
    'Oval, soft jawline',
    'Round, full cheeks',
    'Square, strong jawline',
    'Heart-shaped, narrow chin',
    'Diamond, high cheekbones',
    'Long, narrow',
    'Angular, defined',
  ],
  eyes: [
    'Dark brown, almond',
    'Light brown, round',
    'Hazel, almond',
    'Green, almond',
    'Blue, round',
    'Gray, almond',
    'Amber',
    'Deep-set',
    'Wide-set, round',
    'Hooded',
  ],
  eyebrows: [
    'Black, straight',
    'Brown, arched',
    'Dark, thick',
    'Light, thin',
    'Blonde, soft arch',
    'Auburn, arched',
    'Straight, natural',
  ],
  hair: [
    'Long straight jet black hair',
    'Short black hair',
    'Long wavy brown hair',
    'Shoulder-length brown hair',
    'Long straight blonde hair',
    'Short blonde hair',
    'Curly red hair',
    'Long red hair',
    'Short gray hair',
    'Silver hair',
    'Buzz cut',
    'Bald',
    'Braided hair',
    'Ponytail',
  ],
  nose: [
    'Small, straight',
    'Straight, refined',
    'Slightly upturned',
    'Wide, rounded',
    'Aquiline',
    'Button nose',
  ],
  lips: ['Medium, natural tone', 'Full, natural tone', 'Thin, natural tone', 'Bow-shaped'],
  build: [
    'Slender build',
    'Athletic build',
    'Toned, muscular build',
    'Average build',
    'Curvy build',
    'Stocky build',
    'Heavyset build',
    'Petite build',
  ],
  height_impression: ['Short', 'Below average', 'Average', 'Above average', 'Tall', 'Very tall'],
  base_clothing: [
    'Plain white t-shirt and jeans',
    'Casual button-down shirt and slacks',
    'Simple black dress',
    'Fitted tank top and leggings',
    'Business casual outfit',
    'Fantasy tunic and trousers',
    'Armor and cloak',
  ],
};
